version: '3.8'

services:
  # app:
  #   build: ./orchestrator
  #   ports:
  #     - "8080:8080"
  #   environment:
  #     - DB_HOST=postgres
  #     - DB_USER=myuser
  #     - DB_PASSWORD=mypassword
  #     - DB_NAME=mydb
  #   depends_on:
  #     - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb


    ports:
      - "5432:5432"
    # volumes:
      # - postgres-data:/var/lib/postgresql/data
      # - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

# volumes:
#   postgres-data:
